### ISSUE TITLE
Add readme file.

### ISSUE THREAD

**Issue by div-bargali** [div-bargali/React-Django-To-Do-app#1]
Add a well documented readme file with all required dependancies mentioned and with steps to setup the project and run it locally. The required dependancies are mentioned in requirements.txt for Django server setup.

**Comment by dynamo63** [comment]
:grin: Hi, I would like to be assigned to this task

**Comment by div-bargali** [comment]
@dynamo63 Sure go ahead!

**Comment by div-bargali** [comment]
Fixed in #2 .
